unoplatform/Uno.SourceGeneration

src/Uno.SourceGeneratorTasks.Shared/Content/Uno.SourceGenerationTasks.targets
Makes the clean target injection remove intermediate files, making a rebuild actually start from scratch.
=> Fix clean target is not cleaning intermediate folders

readme.md, src/Uno.SampleProject/Uno.SampleProject.csproj, src/Uno.SourceGenerationHost.Shared/BuildEnvironment.cs, src/Uno.SourceGenerationHost.Shared/ProjectLoader.cs, src/Uno.SourceGenerator.Console/Program.cs, src/Uno.SourceGenerator.Console/Uno.SourceGenerator.Console.csproj, src/Uno.SourceGeneratorTasks.Dev15.0/Uno.SourceGeneratorTasks.Dev15.0.csproj, src/Uno.SourceGeneratorTasks.Shared/Content/Uno.SourceGenerationTasks.targets, src/Uno.SourceGeneratorTasks.Shared/Tasks/SourceGenerationTask.cs
Add support for BinaryLogger in the context of inner msbuild instances, for troubleshooting purposes.
=> Add support for inner-msbuild binlog output generation

src/Uno.SourceGenerationHost.Shared/ProjectLoader.cs
This caused invalid reuse of msbuild project loading results, particularly for cross-targeted projects.
=> Fix invalid cache selection for msbuild project details

src/Uno.SourceGeneratorTasks.Shared/Tasks/SourceGeneratorHostWrapper.cs
This is a workaround for a race condition that can be created when the generation tasks are run inside an AppDomain.
This field https://github.com/Microsoft/msbuild/blob/d8d43bca5bfe28e62c22211ddd1c5578cf3e37f8/src/Build/BackEnd/Components/Scheduler/Scheduler.cs#L1525 is static per app domain, and creates a file that may be discarded in cases of concurrency when the same ID is being used twice, and the following error can happen:
```
UNHANDLED EXCEPTIONS FROM PROCESS 15024:
System.IO.FileNotFoundException: Could not find file 'C:\Users\build-svc-defpool\AppData\Local\Temp\MSBuild15024\Configuration191.cache'.
File name: 'C:\Users\build-svc-defpool\AppData\Local\Temp\MSBuild15024\Configuration191.cache'
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at …
```
=> Add msbuild race condition workaround

src/Uno.SourceGenerator.Console/Program.cs, src/Uno.SourceGeneratorTasks.Shared/Tasks/SourceGenerationTask.cs, src/Uno.SourceGeneratorTasks.Shared/Tasks/SourceGeneratorHostWrapper.cs
Addresses an issues where `AdditionalAssemblies` were incorrectly skipped because of the assembly loading sequence with ApplyCacheFolderMSBuildWorkaround.
=> Fix issue when setting AdditionalAssemblies

src/Uno.SourceGeneration.Host/AssemblyResolver.cs, src/Uno.SourceGeneration.Host/Uno.SourceGeneration.Host.csproj, src/Uno.SourceGenerationHost.Shared/ProjectDetails.cs, src/Uno.SourceGenerationHost.Shared/ProjectLoader.cs, src/Uno.SourceGenerationHost.Shared/SourceGeneratorHost.cs
- Don't reload preloaded assemblies multiple times 
- Update Roslyn to 2.9.0 stable 
- Keep the ProjectCollection alive along the generation
=> Improve diagnostics and reliability

src/Uno.SourceGeneration.Host/Program.cs, src/Uno.SourceGeneratorTasks.Shared/Content/Uno.SourceGenerationTasks.targets, src/Uno.SourceGeneratorTasks.Shared/Tasks/SourceGenerationTask.cs
Ability to capture the console output of the generation, when used.
This feature is opt-in.
=> Improved logging when the host is used.

src/Uno.SourceGeneration.Host/Program.cs, src/Uno.SourceGenerationHost.Shared/Helpers/BinaryLoggerReplayHelper.cs, src/Uno.SourceGeneratorTasks.Shared/Tasks/SourceGenerationTask.cs
Starting from msbuild 16.0 the following error does not happen. Below this version, we continue to use the in-process generation, instead of using the out-of-process generation.
```
System.TypeInitializationException: The type initializer for 'Microsoft.Build.Collections.MSBuildNameIgnoreCaseComparer' threw an exception. ---> System.EntryPointNotFoundException: GetSystemInfo
at(wrapper managed-to-native) Microsoft.Build.Shared.NativeMethodsShared.GetSystemInfo(Microsoft.Build.Shared.NativeMethodsShared/SYSTEM_INFO&)
```
=> Restore current process generation for msbuild below 16.0

.vsts-ci.yml, src/Uno.SourceGeneration.Host/Program.cs, src/Uno.SourceGeneration.Host/Uno.SourceGeneration.Host.csproj, src/Uno.SourceGenerationHost.Shared/ProjectLoader.cs, src/Uno.SourceGenerationHost.Shared/SourceGeneratorHost.cs
- Bugfix
Release builds using the hosted mode fail with `an equivalent project (a project with the same global properties and tools version) has already been loaded`
Release builds are not failing anymore, until an update to Roslyn msbuild workspace is able to discriminate between loaded projects properly.
=> Release builds hosted mode fixes

src/Uno.SourceGeneration.Host/Uno.SourceGeneration.Host.csproj
Fixes #62
- Bugfix
The host process for netcoreapp2.1 does not contain proper dependencies
The host process for netcoreapp2.1 contains proper dependencies, making it run properly for `dotnet build`.
=> Copy all files to the netcoreapp2.1 output folder

build/Uno.SourceGenerationTasks.nuspec
Force the use of netstandard 1.0 for all targets, so the build targets get included in all available TF.
=> Adjust target framework matrix support

build/Uno.SourceGeneration.nuspec, build/Uno.SourceGenerationTasks.nuspec, src/Uno.SampleGenerators/Uno.SampleGenerators.csproj, src/Uno.SampleProject/Uno.SampleProject.csproj, src/Uno.SourceGeneration.Host/AssemblyResolver.cs, src/Uno.SourceGeneration.Host/Uno.SourceGeneration.Host.csproj, src/Uno.SourceGeneration/Uno.SourceGeneration.csproj, src/Uno.SourceGeneratorTasks.Dev15.0/Uno.SourceGeneratorTasks.Dev15.0.csproj, src/Uno.SourceGeneratorTasks.Dev15.0/app.config, src/Uno.SourceGeneratorTasks.Shared/Tasks/SourceGenerationTask.cs
GitHub Issue (If applicable): Closes #70
Adjust package minimum .NET version to 4.6.1, the minimum version to be compatible with .NET Standard 2.0.or internal)
=> Adjust for .NET 4.6.1 minimum for .NET Standard 2.0 compatibility.

src/Uno.FSSampleProject/Library.fs, src/Uno.FSSampleProject/Uno.FSSampleProject.fsproj, src/Uno.SourceGenerator.sln, src/Uno.SourceGeneratorTasks.Shared/Content/Uno.SourceGenerationTasks.targets
This change makes only the csproj projects processed, and ignores the others. This will allow F# projects to use the Uno.UI package (without the Xaml support).
=> Fix support for F# projects

doc/ReleaseNotes/_ReleaseNotes.md, src/Uno.SourceGeneratorTasks.Shared/Content/Uno.SourceGenerationTasks.targets
- Bugfix
Building android project with `AndroidUseIntermediateDesignerFile` set to `true` gives the following false-positive error: 
`Error [Failure] Could not find file 'C:\xxxx.Droid\obj\Debug\80\g\obj\Resource.designer.cs'`
During the loading of a Xamarin.Android project, when AndroidUseIntermediateDesignerFile is set to true, the designer file is added to the compilation list, even though it's not present. This makes the msbuild roslyn workspace try to build this file, raising a error that is not significant as the result of the build is not used. 
This added target removes that file from the compilation list when the project is loaded inside the source generators.
This will fix …
=> Add workaround for unknown android designer file

readme.md, src/Uno.SourceGeneratorTasks.Dev15.0/Content/Uno.SourceGenerationTasks.targets, src/Uno.SourceGeneratorTasks.Dev15.0/Tasks/SourceGenerationTask.cs
Bugfix
If the source generation fails with error code 3, it's not possible to view the exception.
The UnoSourceGeneratoCaptureGenerationHostOutput property is restored, to view the output in the build log.
=> Restore the UnoSourceGeneratoCaptureGenerationHostOutput parameter.

src/Uno.SourceGeneratorTasks.Dev15.0/Tasks/SourceGenerationTask.cs
- Bugfix
Enabling `UnoSourceGeneratorCaptureGenerationHostOutput` shows additional information in the build log.
=> Restore console output for single-use generation

src/Uno.SourceGeneration.Host/Uno.SourceGeneration.Host.csproj
- Bugfix
Getting `The type initializer for 'Microsoft.Build.Collections.MSBuildNameIgnoreCaseComparer' threw an exception.` on macOS.
Tentative use workaround specified here: https://github.com/dotnet/docfx/issues/2358
=> Adjust for macOS build error.

src/Uno.SampleProject/Uno.SampleProject.csproj, src/Uno.SourceGeneratorTasks.Dev15.0/Content/Uno.SourceGenerationTasks.targets
- Bugfix
Disable the use of the generation host when building outside of visual studio. This is a temporary workaround until messages such as those are resolved: 
```
3>Agent01\.nuget\uno.sourcegenerationtasks\1.29.0-dev.235\build\netstandard1.0\Uno.SourceGenerationTasks.targets(99,4): error : Error reading response 
##[error]Agent01\.nuget\uno.sourcegenerationtasks\1.29.0-dev.235\build\netstandard1.0\Uno.SourceGenerationTasks.targets(99,4): Error : Generation failed, error code Rejected
```
=> Use single-use generation host when running outside of VS

build/build.cake, gitversion.yml
GitHub Issue (If applicable): #n/a
- Build or CI related changes
`gitversion` calculates the version for `release/stable` branches as if they are "beta".
`gitversion` should now gives the correct version for each branch.
See : https://github.com/nventive/Uno.Core/pull/54
Internal Issue (If applicable):
https://nventive.visualstudio.com/Umbrella/_workitems/edit/157369
=> fixed gitversion

.vsts-ci.yml, doc/ReleaseNotes/_ReleaseNotes.md, readme.md, src/Uno.SampleCoreApp/Uno.SampleCoreApp.csproj, src/Uno.SampleGenerators/AdditionalPropertiesGenerator.cs, src/Uno.SampleGenerators/Uno.SampleGenerators.csproj, src/Uno.SampleProject.UWP/Uno.SampleProject.UWP.csproj, src/Uno.SampleProject/Uno.SampleProject.csproj, src/Uno.SourceGeneration.Engine.Shared/ProjectLoader.cs, src/Uno.SourceGeneration.Protocol/GenerationClient/BuildEnvironment.cs, src/Uno.SourceGeneratorTasks.Dev15.0/Content/Uno.SourceGenerationTasks.targets, src/Uno.SourceGeneratorTasks.Dev15.0/Tasks/SourceGenerationTask.cs
- Feature
Dynamic or global properties provided to msbuild are not available in the generators' build context, such as `JavaSdkDirectory`.
The introduction of the `UnoSourceGeneratorAdditionalProperty` item group allows for the propagation of those properties to the generators.
Internal Issue (If applicable):
=> Add support for injected or global Property value capture

src/Uno.SourceGeneration.Protocol/Helpers/BinaryLoggerReplayHelper.cs, src/Uno.SourceGeneratorTasks.Dev15.0/Tasks/SourceGenerationTask.cs
- Bugfix
The generation may fail with :
```
System.IO.InvalidDataException: Found invalid data while decoding.
at System.IO.Compression.InflaterZlib.Inflate(FlushCode flushCode)
at System.IO.Compression.InflaterZlib.ReadInflateOutput(Byte[] outputBuffer, Int32 offset, Int32 length, FlushCode flushCode, Int32& bytesRead)
at System.IO.Compression.InflaterZlib.Inflate(Byte[] bytes, Int32 offset, Int32 length)
at System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
at System.IO.Compression.GZipStream.Read(Byte[] array, Int32 offset, Int32 count)
at System.IO.Stream.ReadByte()
at System.IO.BinaryReader.ReadByte()
at Microsoft.Build.Logging.BuildEventArgsReader.Read7BitEncodedInt(BinaryReader reader)
at …
```
=> fix: Failsafe on "Found invalid data while decoding" binlog replay from controller

src/Uno.SourceGeneration.Host/Uno.SourceGeneration.Host.csproj
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/5996
bugfix
VS 16.10 msbuild binaries are referencing a newer version of the `System.Collection.Immutable` assembly.
Internal Issue (If applicable):
=> fix: Bump System.Collections.Immutable to 1.7.1 for VS 19.10 Pre 3 compat

.vsts-ci.yml, src/Uno.FSSampleProject/packages.lock.json, src/Uno.SourceGeneration.Host/Uno.SourceGeneration.Host.csproj
Enables the generation host to follow for preview releases installed in the environment
=> fix: Enable LatestMajor RollForward for source generation host

.vsts-ci.yml, src/Uno.SampleCoreApp/Uno.SampleCoreApp.csproj, src/Uno.SourceGeneratorTasks.Dev15.0/Tasks/SourceGenerationTask.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/9207
- Bugfix
When using a newer (e.g. net7) botnet runtime the task uses this (hardcoded) version to find the host binary (`Uno.SourceGeneration.Host.dll`) to execute.
https://github.com/unoplatform/Uno.SourceGeneration/blob/d859a37defd43065b215a0d2dd3f68f6821e5064/src/Uno.SourceGeneratorTasks.Dev15.0/Tasks/SourceGenerationTask.cs#L384-L387
Assume that newer botnet versions can use the latest, existing binaries (since `<RollForward>LatestMajor</RollForward>` is enabled).
IOW if something newer is detected (e.g. `net7`) then fallback to use `net6` binaries.
The original issue was filed inside the `uno` repository …
=> fix: Select the net6 (latest) binaries if a newer runtime is used
